/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b51bcdf7-1bf2-4212-903f-6e859b48daa3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_rN9EXAE1C",
    "aws_user_pools_web_client_id": "166hprrkfh108gk8595oeuo0tv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rxi56nfstbhzhaasjnujgpcyii.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
