/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ZITBhXIOJ",
    "aws_user_pools_web_client_id": "7k0nolkhe4smtmcq5sc0b5gc9",
    "oauth": {}
};


export default awsmobile;
